name: update-dependencies
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 6 * * *' # daily at 1 am EST/2 am EDT

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - id: update
        uses: DeterminateSystems/update-flake-lock@v20
      - name: Merge
        run: gh pr merge "$PR_NUM" --rebase
        env:
          PR_NUM: ${{ steps.update.outputs.pull-request-number }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
